### ISSUE TITLE
When parsing markdown, add extra newline since in steemit that will break into different lines

### ISSUE THREAD

**Issue by think-in-universe** [steemblog/blog#6]
### Example
crowflew:
* steemblog: https://steemblog.github.io/@crowflew/cn/%E3%80%90%E8%80%81%E4%B9%A6%E8%99%AB%E3%80%914-23%E8%AF%BB%E4%B9%A6%E6%97%A5%E5%92%8C%E5%85%B6%E5%AE%83-%E5%93%81%E4%B9%90%E4%B9%A6%E4%BC%9A-%E6%9C%88%E6%97%A6%E8%AF%84-2018%E5%B9%B44%E6%9C%88%E5%B0%8F%E7%BB%93/
* steemit: https://steemit.com/cn/@crowflew/4-23-or-or-or-2018-4

ericet
* steemblog: https://steemblog.github.io/@ericet/steemit6-9okuim4ews/
* steemit: https://steemit.com/@ericet/steemit6-9okuim4ews/

### Solutions

1. look at steem markdown viewer: [MarkdownViewer](https://github.com/steemit/condenser/blob/fd58e1d526925e048e44ea19d6d91e11a157235e/src/app/components/cards/MarkdownViewer.jsx)
    - [HTMLReady](https://github.com/steemit/condenser/blob/d23d5af2ba83639bf9858660ce0048d2001f5281/src/shared/HtmlReady.js)
1. look at hexo markdown renderer: [hexo-renderer-marked](https://github.com/hexojs/hexo-renderer-marked)
    - configure remarked settings

**Comment by think-in-universe** [comment]
fixed in [commit ](https://github.com/steemblog/blog/commit/9c23c41d71718ba72c1b5905c4c9171b097a83a5), with settings in _config.yml

```yaml
marked:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true
  autolink: true
```
